# Generated by Django 5.1.7 on 2026-08-21 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        # Таблицы уже существуют (созданы приложением pages) и остаются на месте:
        # модели лишь «переезжают» в другое приложение на уровне состояния Django.
        # Физических изменений в базе нет — данные заказчика не затрагиваются.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='HaulerLead',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=120, verbose_name='Имя')),
                        ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                        ('vehicles', models.CharField(blank=True, max_length=200, verbose_name='Техника (тип · количество)')),
                        ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                        ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
                    ],
                    options={
                        'verbose_name': 'Заявка перевозчика',
                        'verbose_name_plural': 'Заявки перевозчиков',
                        'db_table': 'pages_haulerlead',
                        'ordering': ['-created'],
                    },
                ),
                migrations.CreateModel(
                    name='Lead',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=120, verbose_name='Имя')),
                        ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                        ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                        ('details', models.TextField(blank=True, verbose_name='Объект / объём / сроки')),
                        ('page', models.CharField(blank=True, max_length=200, verbose_name='Страница отправки')),
                        ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                        ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
                    ],
                    options={
                        'verbose_name': 'Заявка ТКП',
                        'verbose_name_plural': 'Заявки ТКП',
                        'db_table': 'pages_lead',
                        'ordering': ['-created'],
                    },
                ),
                migrations.CreateModel(
                    name='VacancyApplication',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(max_length=120, verbose_name='Имя')),
                        ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                        ('vacancy_title', models.CharField(blank=True, help_text='Если вакансия выбрана не из списка', max_length=200, verbose_name='Должность (текстом)')),
                        ('resume', models.FileField(blank=True, upload_to='resume/%Y-%m/', verbose_name='Резюме')),
                        ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                        ('created', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                        ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                        ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='content.vacancy', verbose_name='Вакансия')),
                    ],
                    options={
                        'verbose_name': 'Отклик на вакансию',
                        'verbose_name_plural': 'Отклики на вакансии',
                        'db_table': 'pages_vacancyapplication',
                        'ordering': ['-created'],
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
