# Generated by Django 5.1.7 on 2026-08-21 08:29

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # таблицы физически создаёт приложение pages — эти модели
        # лишь переезжают в другое приложение на уровне состояния,
        # поэтому на чистой базе порядок обязан быть именно таким
        ('pages', '0011_fix_price_note'),
    ]

    operations = [
        # Таблицы уже существуют (созданы приложением pages) и остаются на месте:
        # модели лишь «переезжают» в другое приложение на уровне состояния Django.
        # Физических изменений в базе нет — данные заказчика не затрагиваются.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Page',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('slug', models.CharField(help_text='Имя URL — менять не нужно', max_length=60, unique=True, verbose_name='Маршрут')),
                        ('admin_title', models.CharField(help_text='Как называется в этом списке', max_length=120, verbose_name='Страница')),
                        ('h1', models.CharField(blank=True, max_length=250, verbose_name='Заголовок на странице (H1)')),
                        ('subtitle', models.TextField(blank=True, verbose_name='Подзаголовок / вводный текст')),
                        ('body', models.TextField(blank=True, help_text='Для текстовых страниц — политика, согласие. Можно с HTML', verbose_name='Основной текст')),
                        ('seo_title', models.CharField(blank=True, help_text='Если пусто — берётся заголовок страницы', max_length=250, verbose_name='SEO-заголовок (title)')),
                        ('seo_description', models.TextField(blank=True, max_length=400, verbose_name='SEO-описание (description)')),
                    ],
                    options={
                        'verbose_name': 'Страница (тексты и SEO)',
                        'verbose_name_plural': 'Страницы (тексты и SEO)',
                        'db_table': 'pages_page',
                        'ordering': ['admin_title'],
                    },
                ),
                migrations.CreateModel(
                    name='SiteSettings',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('logo_full', models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип полный (для подвала, тёмный фон)')),
                        ('logo_full_light', models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип полный для светлой темы')),
                        ('logo_compact', models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип компактный (шапка, тёмный фон)')),
                        ('logo_compact_light', models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип компактный для светлой темы')),
                        ('logo_mark', models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Знак (иконка вкладки)')),
                        ('phone_main', models.CharField(default='+7 800 000-00-00', max_length=40, verbose_name='Телефон основной')),
                        ('phone_dispatch', models.CharField(blank=True, max_length=40, verbose_name='Диспетчерская бетона')),
                        ('phone_upex', models.CharField(blank=True, max_length=40, verbose_name='Отдел опалубки UPEX')),
                        ('email_main', models.EmailField(blank=True, max_length=254, verbose_name='E-mail основной')),
                        ('email_sales', models.EmailField(blank=True, max_length=254, verbose_name='E-mail отдела продаж')),
                        ('email_hr', models.EmailField(blank=True, max_length=254, verbose_name='E-mail отдела кадров')),
                        ('address_office', models.CharField(blank=True, max_length=250, verbose_name='Адрес офиса')),
                        ('address_plant', models.CharField(blank=True, max_length=250, verbose_name='Адрес завода')),
                        ('address_quarry', models.CharField(blank=True, max_length=250, verbose_name='Адрес карьера')),
                        ('work_hours', models.CharField(blank=True, help_text='Например: пн–сб 8:00–18:00, в сезон — круглосуточно', max_length=150, verbose_name='Режим работы')),
                        ('slogan', models.CharField(default='Строим основу будущего.', max_length=150, verbose_name='Слоган')),
                        ('founded_year', models.PositiveIntegerField(blank=True, help_text='Подставляется в текст «С … года поставляем бетон…»', null=True, verbose_name='Год основания')),
                        ('legal_name', models.CharField(default='ЗАО «Стройдеталь-2»', max_length=250, verbose_name='Юридическое лицо')),
                        ('copyright_note', models.CharField(blank=True, default='ГАНИН ГРУПП — маркетинговый бренд группы.', max_length=250, verbose_name='Приписка в копирайте')),
                        ('footer_about', models.TextField(blank=True, default='Бетон, ЖБИ, асфальт, опалубка, карьер, транспорт — под единым брендом. База на КМВ, поставки по СКФО и всей России.', verbose_name='Текст в подвале под логотипом')),
                        ('upex_url', models.URLField(blank=True, help_text='Ссылка в меню «Опалубка (UPEX) ↗»', verbose_name='Сайт опалубки UPEX')),
                        ('messenger_url', models.CharField(blank=True, max_length=250, verbose_name='Ссылка мессенджера (кнопка MAX)')),
                        ('price_note', models.CharField(blank=True, default='Окончательная стоимость зависит от объёма, графика поставок и удалённости объекта.', help_text='Показывается под результатом калькулятора. Фраза про доставку добавляется автоматически — в зависимости от того, выбрал её клиент или нет', max_length=300, verbose_name='Оговорка про цены')),
                        ('price_valid_from', models.DateField(blank=True, help_text='Дата из прайс-листа — выводится рядом с результатом', null=True, verbose_name='Цены действуют с')),
                        ('notify_emails', models.CharField(blank=True, help_text='Один или несколько адресов через запятую. Пусто — письма не отправляются', max_length=400, verbose_name='Куда слать заявки (почта)')),
                        ('telegram_token', models.CharField(blank=True, help_text='Получить у @BotFather. Пусто — в телеграм не отправляется', max_length=200, verbose_name='Токен телеграм-бота')),
                        ('telegram_chat_id', models.CharField(blank=True, help_text='Куда бот пришлёт заявку: ваш ID или ID группы', max_length=100, verbose_name='ID чата в телеграме')),
                    ],
                    options={
                        'verbose_name': 'Общие данные сайта',
                        'verbose_name_plural': 'Общие данные сайта',
                        'db_table': 'pages_sitesettings',
                    },
                ),
                migrations.CreateModel(
                    name='MenuItem',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=120, verbose_name='Название')),
                        ('url_name', models.CharField(blank=True, help_text='Имя URL, например produkciya_beton', max_length=60, verbose_name='Маршрут')),
                        ('external_url', models.URLField(blank=True, help_text='Если ведёт на другой сайт (UPEX)', verbose_name='Внешняя ссылка')),
                        ('footer_title', models.CharField(blank=True, help_text='Если пусто — берётся название. «Продукция» в подвале называется «Направления»', max_length=120, verbose_name='Заголовок колонки в подвале')),
                        ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в подвале')),
                        ('parent', models.ForeignKey(blank=True, help_text='Пусто — пункт верхнего уровня', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.menuitem', verbose_name='Раздел')),
                    ],
                    options={
                        'verbose_name': 'Пункт меню',
                        'verbose_name_plural': 'Меню сайта',
                        'db_table': 'pages_menuitem',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Card',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('section', models.CharField(default='main', help_text='Ключ секции — если на странице несколько сеток', max_length=60, verbose_name='Блок на странице')),
                        ('icon', models.CharField(blank=True, help_text='Короткая подпись в квадрате, например 01 или ↗', max_length=20, verbose_name='Индекс / иконка')),
                        ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                        ('text', models.TextField(blank=True, verbose_name='Текст')),
                        ('url_name', models.CharField(blank=True, help_text='Имя URL, если плитка ведёт на страницу', max_length=60, verbose_name='Маршрут ссылки')),
                        ('link_label', models.CharField(blank=True, max_length=100, verbose_name='Подпись ссылки')),
                        ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to='core.page', verbose_name='Страница')),
                    ],
                    options={
                        'verbose_name': 'Плитка на странице',
                        'verbose_name_plural': 'Плитки на страницах',
                        'db_table': 'pages_card',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
