# Generated by Django 5.1.7 on 2026-08-21 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='requisites',
            field=models.CharField(blank=True, help_text='Строкой, например: ИНН 2600000000 · ОГРН 1022600000000. Показывается на странице «Контакты»', max_length=250, verbose_name='Реквизиты (ИНН, ОГРН)'),
        ),
    ]
