# Generated by Django 5.1.7 on 2026-08-31 09:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings_requisites'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='photo',
            field=models.ImageField(blank=True, help_text='Для плиток с местом под фото (например, активы на «О группе»)', upload_to='cards/', verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='page',
            name='photo',
            field=models.ImageField(blank=True, help_text='Главное фото: фон шапки у решений и кейса, фото слева у сервисов, главное фото товара на карточке. Если пусто — серая заглушка', upload_to='pages/', verbose_name='Фото страницы'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_photo',
            field=models.ImageField(blank=True, help_text='Показывается на телефонах и пока видео не загружено', upload_to='hero/', verbose_name='Фото первого экрана'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_video',
            field=models.FileField(blank=True, help_text='Фоновое видео на главной (без звука, короткий ролик). Если пусто — показывается фото или заглушка', upload_to='hero/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm'], message='Видео принимаем в MP4 или WEBM.')], verbose_name='Видео первого экрана'),
        ),
        migrations.CreateModel(
            name='PagePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('image', models.ImageField(upload_to='pages/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, help_text='Например: этап заливки — что видно на снимке', max_length=200, verbose_name='Подпись')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='core.page', verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Фото в галерее страницы',
                'verbose_name_plural': 'Фото в галереях страниц',
                'db_table': 'pages_pagephoto',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
