# Generated by Django 5.1.7 on 2026-08-31 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_card_photo_page_photo_sitesettings_hero_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?ll=42.986830%2C44.061033&z=16&pt=42.986830,44.061033,pm2orgl', help_text='Карта на «Контактах» и главной. Свою карту (с зоной доставки, несколькими метками) можно собрать в Конструкторе карт Яндекса и вставить сюда ссылку из кнопки «Получить код» (адрес из src). Пусто — вернётся схема-заглушка вёрстки', max_length=500, verbose_name='Ссылка встройки Яндекс.Карты'),
        ),
    ]
