# Generated by Django 5.1.7 on 2026-08-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sitesettings_map_embed_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='map_api_key',
            field=models.CharField(blank=True, help_text='С ключом карта рисуется через JS API: метка завода + круг зоны доставки 200 км. Бесплатный ключ — developer.tech.yandex.ru, сервис «JavaScript API и HTTP Геокодер». Пусто — простой виджет по ссылке ниже', max_length=100, verbose_name='API-ключ Яндекс.Карт (JavaScript API)'),
        ),
    ]
