# Generated by Django 5.1.7 on 2026-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_map_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_radius_km',
            field=models.PositiveIntegerField(default=200, help_text='Круг зоны покрытия на карте главной (бетон и инертные). Работает при заполненном API-ключе', verbose_name='Радиус зоны доставки, км'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='map_embed_url',
            field=models.URLField(blank=True, default='https://yandex.ru/map-widget/v1/?ll=42.986830%2C44.061033&z=16&pt=42.986830,44.061033,pm2orgl', help_text='Запасной вариант, если API-ключа нет: простой виджет карты. С заполненным ключом выше — не используется. Пусто и без ключа — схема-заглушка вёрстки', max_length=500, verbose_name='Ссылка встройки Яндекс.Карты (без ключа)'),
        ),
    ]
