# Generated by Django 5.1.7 on 2026-09-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_sitesettings_delivery_radius_km_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='noindex',
            field=models.BooleanField(default=True, help_text='Пока включено — сайт не индексируется (meta noindex на всех страницах + robots.txt Disallow). Снимите галочку при запуске на рабочем домене, чтобы сайт попал в поиск', verbose_name='Закрыть сайт от поисковиков'),
        ),
    ]
