# Generated by Django 5.1.7 on 2026-08-14 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HaulerLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('vehicles', models.CharField(blank=True, max_length=200, verbose_name='Техника (тип · количество)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка перевозчика',
                'verbose_name_plural': 'Заявки перевозчиков',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('details', models.TextField(blank=True, verbose_name='Объект / объём / сроки')),
                ('page', models.CharField(blank=True, max_length=200, verbose_name='Страница отправки')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработана')),
            ],
            options={
                'verbose_name': 'Заявка ТКП',
                'verbose_name_plural': 'Заявки ТКП',
                'ordering': ['-created'],
            },
        ),
    ]
