# Generated by Django 5.1.7 on 2026-08-14 09:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_department_direction_document_mappoint_page_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('url_name', models.CharField(blank=True, help_text='Имя URL, например produkciya_beton', max_length=60, verbose_name='Маршрут')),
                ('external_url', models.URLField(blank=True, help_text='Если ведёт на другой сайт (UPEX)', verbose_name='Внешняя ссылка')),
                ('footer_title', models.CharField(blank=True, help_text='Если пусто — берётся название. «Продукция» в подвале называется «Направления»', max_length=120, verbose_name='Заголовок колонки в подвале')),
                ('show_in_footer', models.BooleanField(default=True, verbose_name='Показывать в подвале')),
                ('parent', models.ForeignKey(blank=True, help_text='Пусто — пункт верхнего уровня', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='pages.menuitem', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'Пункт меню',
                'verbose_name_plural': 'Меню сайта',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
