# Generated by Django 5.1.7 on 2026-08-14 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_menuitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='VacancyApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Имя')),
                ('phone', models.CharField(max_length=40, verbose_name='Телефон')),
                ('vacancy_title', models.CharField(blank=True, help_text='Если вакансия выбрана не из списка', max_length=200, verbose_name='Должность (текстом)')),
                ('resume', models.FileField(blank=True, upload_to='resume/%Y-%m/', verbose_name='Резюме')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Получен')),
                ('processed', models.BooleanField(default=False, verbose_name='Обработан')),
                ('vacancy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='pages.vacancy', verbose_name='Вакансия')),
            ],
            options={
                'verbose_name': 'Отклик на вакансию',
                'verbose_name_plural': 'Отклики на вакансии',
                'ordering': ['-created'],
            },
        ),
    ]
