# Generated by Django 5.1.7 on 2026-08-14 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_vacancyapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='notify_emails',
            field=models.CharField(blank=True, help_text='Один или несколько адресов через запятую. Пусто — письма не отправляются', max_length=400, verbose_name='Куда слать заявки (почта)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_chat_id',
            field=models.CharField(blank=True, help_text='Куда бот пришлёт заявку: ваш ID или ID группы', max_length=100, verbose_name='ID чата в телеграме'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='telegram_token',
            field=models.CharField(blank=True, help_text='Получить у @BotFather. Пусто — в телеграм не отправляется', max_length=200, verbose_name='Токен телеграм-бота'),
        ),
    ]
