# Generated by Django 5.1.7 on 2026-08-14 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_sitesettings_notify_emails_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_compact',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип компактный (шапка, тёмный фон)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_compact_light',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип компактный для светлой темы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_full',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип полный (для подвала, тёмный фон)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_full_light',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Логотип полный для светлой темы'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo_mark',
            field=models.FileField(blank=True, upload_to='logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['svg', 'png', 'jpg', 'jpeg', 'webp'], message='Логотип принимаем в SVG, PNG, JPG или WEBP.')], verbose_name='Знак (иконка вкладки)'),
        ),
    ]
