# Generated by Django 5.1.7 on 2026-08-14 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_sitesettings_logo_compact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConcreteGrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(help_text='Например: М300', max_length=40, verbose_name='Марка')),
                ('grade_class', models.CharField(blank=True, help_text='Например: В22,5 W4', max_length=40, verbose_name='Класс')),
                ('price', models.PositiveIntegerField(blank=True, help_text='Без доставки. Пусто — вместо цены покажем «по запросу»', null=True, verbose_name='Цена от, ₽ за м³')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбрана по умолчанию')),
            ],
            options={
                'verbose_name': 'Марка бетона и цена',
                'verbose_name_plural': 'Марки бетона и цены',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_note',
            field=models.CharField(blank=True, default='Цены указаны без доставки. Окончательная стоимость зависит от объёма, графика поставок и удалённости объекта.', help_text='Показывается под результатом калькулятора', max_length=300, verbose_name='Оговорка про цены'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='price_valid_from',
            field=models.DateField(blank=True, help_text='Дата из прайс-листа — выводится рядом с результатом', null=True, verbose_name='Цены действуют с'),
        ),
    ]
