# Generated by Django 5.1.7 on 2026-08-21 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_concretegrade_sitesettings_price_note_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(help_text='Через запятую — как в прайсе', max_length=250, verbose_name='Населённые пункты')),
                ('price_per_m3', models.PositiveIntegerField(blank=True, null=True, verbose_name='От 5 м³ — цена за 1 м³, ₽')),
                ('price_trip', models.PositiveIntegerField(blank=True, null=True, verbose_name='До 5 м³ — цена за рейс, ₽')),
                ('price_trip_small', models.PositiveIntegerField(blank=True, help_text='Справочно: применяется при ограниченном подъезде', null=True, verbose_name='Маленький миксер до 3 м³ — за рейс, ₽')),
            ],
            options={
                'verbose_name': 'Зона доставки',
                'verbose_name_plural': 'Доставка по зонам',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
