# Generated by Django 5.1.7 on 2026-08-21 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_seed_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='price_note',
            field=models.CharField(blank=True, default='Окончательная стоимость зависит от объёма, графика поставок и удалённости объекта.', help_text='Показывается под результатом калькулятора. Фраза про доставку добавляется автоматически — в зависимости от того, выбрал её клиент или нет', max_length=300, verbose_name='Оговорка про цены'),
        ),
    ]
