# Generated by Django 5.1.7 on 2026-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        # таблицы физически создаёт приложение pages — эти модели
        # лишь переезжают в другое приложение на уровне состояния,
        # поэтому на чистой базе порядок обязан быть именно таким
        ('pages', '0011_fix_price_note'),
    ]

    operations = [
        # Таблицы уже существуют (созданы приложением pages) и остаются на месте:
        # модели лишь «переезжают» в другое приложение на уровне состояния Django.
        # Физических изменений в базе нет — данные заказчика не затрагиваются.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Department',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=150, verbose_name='Отдел')),
                        ('person', models.CharField(blank=True, max_length=150, verbose_name='Сотрудник')),
                        ('position', models.CharField(blank=True, max_length=150, verbose_name='Должность')),
                        ('phone', models.CharField(blank=True, max_length=40, verbose_name='Телефон')),
                        ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                        ('photo', models.ImageField(blank=True, upload_to='people/', verbose_name='Фото')),
                    ],
                    options={
                        'verbose_name': 'Отдел (контакты)',
                        'verbose_name_plural': 'Отделы (контакты)',
                        'db_table': 'pages_department',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Direction',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=120, verbose_name='Название')),
                        ('tagline', models.CharField(blank=True, max_length=250, verbose_name='Короткое описание')),
                        ('photo', models.ImageField(blank=True, help_text='Если пусто — покажется серая плитка-заглушка', upload_to='directions/', verbose_name='Фото')),
                        ('url_name', models.CharField(blank=True, help_text='Имя URL, например produkciya_beton. Пусто — плитка без ссылки', max_length=60, verbose_name='Маршрут страницы')),
                        ('external_url', models.URLField(blank=True, help_text='Для UPEX — адрес отдельного сайта', verbose_name='Внешняя ссылка')),
                        ('size', models.CharField(blank=True, choices=[('', 'обычная'), ('big', 'большая'), ('tall', 'высокая')], default='', max_length=10, verbose_name='Размер плитки')),
                        ('is_upex', models.BooleanField(default=False, verbose_name='Это UPEX (особый стиль плитки)')),
                    ],
                    options={
                        'verbose_name': 'Направление',
                        'verbose_name_plural': 'Направления (продукция)',
                        'db_table': 'pages_direction',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Document',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=200, verbose_name='Название')),
                        ('kind', models.CharField(blank=True, help_text='Например: PDF, DOC', max_length=40, verbose_name='Тип')),
                        ('summary', models.CharField(blank=True, max_length=250, verbose_name='Пояснение')),
                        ('file', models.FileField(blank=True, upload_to='docs/', verbose_name='Файл')),
                    ],
                    options={
                        'verbose_name': 'Документ',
                        'verbose_name_plural': 'Документы',
                        'db_table': 'pages_document',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='MapPoint',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=120, verbose_name='Город / площадка')),
                        ('left', models.PositiveIntegerField(default=50, help_text='0–100 — где точка стоит на карте', verbose_name='Позиция слева, %')),
                        ('top', models.PositiveIntegerField(default=50, verbose_name='Позиция сверху, %')),
                        ('is_own', models.BooleanField(default=False, verbose_name='Своя площадка (не просто поставка)')),
                    ],
                    options={
                        'verbose_name': 'Точка на карте',
                        'verbose_name_plural': 'Карта присутствия',
                        'db_table': 'pages_mappoint',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='ProjectObject',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=200, verbose_name='Название объекта')),
                        ('slug', models.SlugField(blank=True, max_length=200, unique=True, verbose_name='Адрес страницы')),
                        ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                        ('direction', models.CharField(blank=True, help_text='Например: бетон, опалубка, асфальт', max_length=100, verbose_name='Направление')),
                        ('summary', models.CharField(blank=True, max_length=250, verbose_name='Кратко (в карточке)')),
                        ('photo', models.ImageField(blank=True, upload_to='objects/', verbose_name='Фото объекта')),
                        ('year', models.CharField(blank=True, max_length=40, verbose_name='Год / период')),
                        ('volume', models.CharField(blank=True, max_length=100, verbose_name='Объём поставки')),
                        ('is_featured', models.BooleanField(default=False, verbose_name='Показать на главной')),
                    ],
                    options={
                        'verbose_name': 'Объект',
                        'verbose_name_plural': 'Объекты',
                        'db_table': 'pages_projectobject',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Review',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('text', models.TextField(help_text='Часть фразы можно выделить: обернуть в <em>…</em>', verbose_name='Текст отзыва')),
                        ('author', models.CharField(blank=True, max_length=150, verbose_name='Автор')),
                        ('author_role', models.CharField(blank=True, max_length=200, verbose_name='Должность / компания')),
                        ('photo', models.ImageField(blank=True, upload_to='people/', verbose_name='Фото автора')),
                        ('is_featured', models.BooleanField(default=False, verbose_name='Показать на главной')),
                    ],
                    options={
                        'verbose_name': 'Отзыв',
                        'verbose_name_plural': 'Отзывы',
                        'db_table': 'pages_review',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Stat',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('value', models.CharField(help_text='Например: 150 или 293', max_length=30, verbose_name='Значение')),
                        ('sup', models.CharField(blank=True, help_text='Например: 000 м³ — выводится мелким оранжевым', max_length=20, verbose_name='Приписка сверху')),
                        ('label', models.CharField(help_text='Например: м³ бетона и раствора в год', max_length=200, verbose_name='Подпись')),
                        ('note', models.CharField(blank=True, max_length=200, verbose_name='Уточнение')),
                    ],
                    options={
                        'verbose_name': 'Цифра холдинга',
                        'verbose_name_plural': 'Цифры холдинга',
                        'db_table': 'pages_stat',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='TeamMember',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('name', models.CharField(max_length=150, verbose_name='Имя и фамилия')),
                        ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                        ('photo', models.ImageField(blank=True, upload_to='people/', verbose_name='Фото')),
                        ('is_featured', models.BooleanField(default=True, verbose_name='Показать на главной')),
                    ],
                    options={
                        'verbose_name': 'Руководитель',
                        'verbose_name_plural': 'Команда',
                        'db_table': 'pages_teammember',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='TimelineEvent',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('year', models.CharField(max_length=40, verbose_name='Год')),
                        ('title', models.CharField(max_length=200, verbose_name='Событие')),
                        ('text', models.TextField(blank=True, verbose_name='Описание')),
                    ],
                    options={
                        'verbose_name': 'Событие истории',
                        'verbose_name_plural': 'История группы',
                        'db_table': 'pages_timelineevent',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='Vacancy',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(max_length=200, verbose_name='Должность')),
                        ('kind', models.CharField(blank=True, help_text='Например: производство, транспорт, офис', max_length=60, verbose_name='Метка')),
                        ('summary', models.CharField(blank=True, max_length=250, verbose_name='Кратко')),
                        ('salary', models.CharField(blank=True, max_length=100, verbose_name='Зарплата')),
                        ('description', models.TextField(blank=True, verbose_name='Описание')),
                    ],
                    options={
                        'verbose_name': 'Вакансия',
                        'verbose_name_plural': 'Вакансии',
                        'db_table': 'pages_vacancy',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
