# Generated by Django 5.1.7 on 2026-08-31 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('section', models.CharField(choices=[('produkciya_beton', 'Бетон'), ('produkciya_zhbi', 'ЖБИ'), ('produkciya_asfalt', 'Асфальт'), ('produkciya_inertnye', 'Инертные материалы')], max_length=40, verbose_name='Раздел каталога')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('chips', models.CharField(blank=True, help_text='Короткие метки через « · », например: W4 · П3–П4', max_length=200, verbose_name='Бейджи')),
                ('photo', models.ImageField(blank=True, help_text='Если пусто — покажется серая плитка-заглушка', upload_to='catalog/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Позиция каталога',
                'verbose_name_plural': 'Каталог продукции',
                'db_table': 'pages_catalogitem',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
