# Generated by Django 5.1.7 on 2026-08-31 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_catalogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='mappoint',
            name='lat',
            field=models.FloatField(blank=True, help_text='Например 44.0610 (для Яндекс.Карты). Координаты можно скопировать из Яндекс.Карт: правый клик по точке → «Что здесь?»', null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='mappoint',
            name='lng',
            field=models.FloatField(blank=True, help_text='Например 42.9868', null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='is_own',
            field=models.BooleanField(default=False, help_text='Отмечается крупной оранжевой меткой', verbose_name='Своя площадка (завод, карьер)'),
        ),
        migrations.AlterField(
            model_name='mappoint',
            name='left',
            field=models.PositiveIntegerField(default=50, help_text='0–100 — для схематичной карты без ключа', verbose_name='Позиция слева, %'),
        ),
    ]
