# Generated by Django 5.1.7 on 2026-08-31 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_seed_mappoint_coords'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='challenge',
            field=models.TextField(blank=True, verbose_name='Вызов'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='context',
            field=models.TextField(blank=True, verbose_name='Контекст'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='headline',
            field=models.CharField(blank=True, help_text='Крупный заголовок на странице объекта. Пусто — берётся название', max_length=250, verbose_name='Заголовок кейса (H1)'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='quote_author',
            field=models.CharField(blank=True, max_length=150, verbose_name='Автор отзыва'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='quote_role',
            field=models.CharField(blank=True, max_length=200, verbose_name='Должность / компания'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='quote_text',
            field=models.TextField(blank=True, help_text='Часть можно выделить: <em>…</em>', verbose_name='Отзыв по объекту'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='result',
            field=models.TextField(blank=True, verbose_name='Результат'),
        ),
        migrations.AddField(
            model_name='projectobject',
            name='solution',
            field=models.TextField(blank=True, verbose_name='Решение'),
        ),
        migrations.AlterField(
            model_name='projectobject',
            name='photo',
            field=models.ImageField(blank=True, help_text='Обложка карточки и главное фото на странице кейса', upload_to='objects/', verbose_name='Фото объекта'),
        ),
        migrations.CreateModel(
            name='ObjectPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('image', models.ImageField(upload_to='objects/gallery/', verbose_name='Фото')),
                ('caption', models.CharField(blank=True, help_text='Например: этап заливки — что видно на снимке', max_length=200, verbose_name='Подпись')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_photos', to='content.projectobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Фото объекта',
                'verbose_name_plural': 'Фото объекта',
                'db_table': 'pages_objectphoto',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ObjectStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('value', models.CharField(help_text='Например: 20 или 24/7', max_length=30, verbose_name='Значение')),
                ('sup', models.CharField(blank=True, help_text='Например: тыс — мелким оранжевым', max_length=20, verbose_name='Приписка сверху')),
                ('label', models.CharField(help_text='Например: м³ бетона поставлено', max_length=200, verbose_name='Подпись')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Уточнение')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='content.projectobject', verbose_name='Объект')),
            ],
            options={
                'verbose_name': 'Цифра объекта',
                'verbose_name_plural': 'Цифры объекта',
                'db_table': 'pages_objectstat',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
