# Generated by Django 5.1.7 on 2026-08-31 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_seed_documents'),
    ]

    operations = [
        migrations.AddField(
            model_name='direction',
            name='asset_text',
            field=models.CharField(blank=True, help_text='Пусто — берётся короткое описание направления', max_length=250, verbose_name='Описание в активах'),
        ),
        migrations.AddField(
            model_name='direction',
            name='asset_title',
            field=models.CharField(blank=True, help_text='Если в активах называется иначе — напр. «Бетонный завод» вместо «Бетон». Пусто — как основное название', max_length=120, verbose_name='Заголовок в активах'),
        ),
        migrations.AddField(
            model_name='direction',
            name='show_in_assets',
            field=models.BooleanField(default=False, help_text='Плитка появится в блоке активов на «О группе» — с этим же фото, загружать второй раз не нужно', verbose_name='Показывать в «Производственных активах» (О группе)'),
        ),
    ]
