# Generated by Django 5.1.7 on 2026-09-08 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_seed_direction_assets'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectobject',
            name='segments',
            field=models.CharField(blank=True, help_text='На каких страницах раздела «Решения» показывать объект в блоке «Объекты сегмента». Можно отметить несколько', max_length=250, verbose_name='Сегменты'),
        ),
    ]
