# Generated by Django 5.1.7 on 2026-08-21 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # Таблицы уже существуют (созданы приложением pages) и остаются на месте:
        # модели лишь «переезжают» в другое приложение на уровне состояния Django.
        # Физических изменений в базе нет — данные заказчика не затрагиваются.
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='ConcreteGrade',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(help_text='Например: М300', max_length=40, verbose_name='Марка')),
                        ('grade_class', models.CharField(blank=True, help_text='Например: В22,5 W4', max_length=40, verbose_name='Класс')),
                        ('price', models.PositiveIntegerField(blank=True, help_text='Без доставки. Пусто — вместо цены покажем «по запросу»', null=True, verbose_name='Цена от, ₽ за м³')),
                        ('note', models.CharField(blank=True, max_length=200, verbose_name='Примечание')),
                        ('is_default', models.BooleanField(default=False, verbose_name='Выбрана по умолчанию')),
                    ],
                    options={
                        'verbose_name': 'Марка бетона и цена',
                        'verbose_name_plural': 'Марки бетона и цены',
                        'db_table': 'pages_concretegrade',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
                migrations.CreateModel(
                    name='DeliveryZone',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                        ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                        ('title', models.CharField(help_text='Через запятую — как в прайсе', max_length=250, verbose_name='Населённые пункты')),
                        ('price_per_m3', models.PositiveIntegerField(blank=True, null=True, verbose_name='От 5 м³ — цена за 1 м³, ₽')),
                        ('price_trip', models.PositiveIntegerField(blank=True, null=True, verbose_name='До 5 м³ — цена за рейс, ₽')),
                        ('price_trip_small', models.PositiveIntegerField(blank=True, help_text='Справочно: применяется при ограниченном подъезде', null=True, verbose_name='Маленький миксер до 3 м³ — за рейс, ₽')),
                    ],
                    options={
                        'verbose_name': 'Зона доставки',
                        'verbose_name_plural': 'Доставка по зонам',
                        'db_table': 'pages_deliveryzone',
                        'ordering': ['order', 'id'],
                        'abstract': False,
                    },
                ),
            ],
            database_operations=[],
        ),
    ]
