# Generated by Django 5.1.7 on 2026-08-21 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=100, help_text='Меньше — выше в списке', verbose_name='Порядок')),
                ('published', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('title', models.CharField(max_length=60, verbose_name='Название')),
                ('pic', models.CharField(blank=True, help_text='Один символ для кнопки, например ▭', max_length=4, verbose_name='Значок')),
                ('formula', models.CharField(choices=[('box', 'Три размера: A × B × C (плита, лента, стена, колонна)'), ('cylinder', 'Круглое сечение: π × (A ÷ 2)² × B (свая)'), ('half', 'Половина объёма: A × B × C ÷ 2 (лестница)')], default='box', max_length=20, verbose_name='Как считать')),
                ('label_a', models.CharField(default='Длина', max_length=60, verbose_name='Подпись 1-го поля')),
                ('label_b', models.CharField(default='Ширина', max_length=60, verbose_name='Подпись 2-го поля')),
                ('label_c', models.CharField(blank=True, default='Толщина', help_text='Пусто — третье поле не показывается (для сваи)', max_length=60, verbose_name='Подпись 3-го поля')),
                ('use_count', models.BooleanField(default=False, help_text='Для свай, колонн, лестничных маршей', verbose_name='Спрашивать количество')),
                ('hint', models.CharField(blank=True, max_length=200, verbose_name='Подсказка под полями')),
                ('is_default', models.BooleanField(default=False, verbose_name='Выбран по умолчанию')),
            ],
            options={
                'verbose_name': 'Тип конструкции',
                'verbose_name_plural': 'Типы конструкций (калькулятор)',
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
